[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/gm/*"
  to = "/login"
  status = 302
  force = true
  conditions = {Role = ["gm"]}

[[headers]]
  for = "/gm/*"
  [headers.values]
  Cache-Control = "no-cache"
