[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "22"

# netlify.toml

# 1) Redirect *host* vaughnrpgs.com → www.vaughnrpgs.com (all paths)
[[redirects]]
  from = "/*"
  to = "https://www.vaughnrpgs.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["vaughnrpgs.com"] }

[[headers]]
  for = "/gm/*"
  [headers.values]
  Cache-Control = "no-cache"
